# abachurin, Dec 19 2022

name: Build container on my Docker Hub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-back:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Set up QEMU dependency
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: abachurin/ui_2048:latest
        platforms: linux/arm/v8
        push: true
#      run: docker buildx build -t $USER/$REPO:latest --platform linux/arm/v8
#      run: docker build . -t $USER/$REPO:latest --platform linux/arm64/v8

#    - name: Push to Docker Hub
#      run: docker push $USER/$REPO:latest
